version: "3.2"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: 'mosquitto-broker'
    ports:
        - 8443:8883
    volumes:
        - ./:/mosquitto/:rw
    networks:
        - proxy

  tlaas:
    build: web
    container_name: 'tlaas-web'
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.tlaas-web.rule=Host(`tlaas.hosting.csta.cisco.com`)"
        - "traefik.http.routers.tlaas-web.service=tlaas-web"
        - "traefik.http.services.tlaas-web.loadbalancer.server.port=80"
    volumes:
        - ./templates:/templates:ro
        - ./static:/static:ro
    networks:
        - proxy

networks:
  proxy:
    external: true
